-- =============================================================================
-- PHARMACOVIGILANCE DATA QUALITY SYSTEM - DATABASE SCHEMA
-- =============================================================================
-- This schema supports Agent 2 (Data Quality & Confidence Control)
-- for the WhatsApp-based pharmacovigilance follow-up system.
--
-- Tables:
--   1. Patient - Patient demographics
--   2. Doctor - Doctor information
--   3. Visit - Visit records linking patients and doctors
--   4. Doctor_Entry - Doctor-entered clinical data
--   5. Patient_Response - Patient responses from Agent 1 conversations
--   6. Data_Quality_Report - Quality reports generated by Agent 2
--   7. Clarification_Request - Pending clarification requests
-- =============================================================================


-- -----------------------------------------------------------------------------
-- TABLE: Patient
-- Stores patient demographic information
-- -----------------------------------------------------------------------------
CREATE TABLE Patient (
    patient_id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    email VARCHAR(255),                          -- Email for form delivery
    preferred_language VARCHAR(10) DEFAULT 'en', -- Language preference (en, hi, ta, te, ml)
    age INT,
    gender VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_patient_phone ON Patient(phone_number);
CREATE INDEX idx_patient_email ON Patient(email);


-- -----------------------------------------------------------------------------
-- TABLE: Doctor
-- Stores doctor/healthcare provider information
-- -----------------------------------------------------------------------------
CREATE TABLE Doctor (
    doctor_id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    department VARCHAR(100),
    hospital_id INT,
    email VARCHAR(255),
    phone_number VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_doctor_hospital ON Doctor(hospital_id);


-- -----------------------------------------------------------------------------
-- TABLE: Visit
-- Records each patient visit, linking patient and doctor
-- -----------------------------------------------------------------------------
CREATE TABLE Visit (
    visit_id INT PRIMARY KEY AUTO_INCREMENT,
    patient_id VARCHAR(50) NOT NULL,
    doctor_id INT NOT NULL,
    visit_date DATE NOT NULL,
    visit_type VARCHAR(50) NOT NULL CHECK (visit_type IN ('new', 'follow-up', 'side-effect')),
    disease_name VARCHAR(255),
    status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'abandoned')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (patient_id) REFERENCES Patient(patient_id) ON DELETE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES Doctor(doctor_id) ON DELETE CASCADE
);

CREATE INDEX idx_visit_patient ON Visit(patient_id);
CREATE INDEX idx_visit_doctor ON Visit(doctor_id);
CREATE INDEX idx_visit_date ON Visit(visit_date);
CREATE INDEX idx_visit_status ON Visit(status);


-- -----------------------------------------------------------------------------
-- TABLE: Doctor_Entry
-- Stores doctor-entered clinical data for each visit
-- One-to-one relationship with Visit
-- -----------------------------------------------------------------------------
CREATE TABLE Doctor_Entry (
    visit_id INT PRIMARY KEY,
    diagnosis_notes TEXT,
    medicine_prescribed VARCHAR(255) NOT NULL,
    dosage VARCHAR(100),
    frequency VARCHAR(100),
    duration VARCHAR(100),
    additional_instructions TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (visit_id) REFERENCES Visit(visit_id) ON DELETE CASCADE
);


-- -----------------------------------------------------------------------------
-- TABLE: Patient_Response
-- Stores all patient responses collected by Agent 1 (Conversational Agent)
-- Each question-answer pair is stored as a separate row
-- -----------------------------------------------------------------------------
CREATE TABLE Patient_Response (
    response_id INT PRIMARY KEY AUTO_INCREMENT,
    visit_id INT NOT NULL,
    question_id VARCHAR(100) NOT NULL,
    answer TEXT NOT NULL,
    language VARCHAR(50) DEFAULT 'english',
    response_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (visit_id) REFERENCES Visit(visit_id) ON DELETE CASCADE
);

CREATE INDEX idx_response_visit ON Patient_Response(visit_id);
CREATE INDEX idx_response_question ON Patient_Response(question_id);
CREATE INDEX idx_response_timestamp ON Patient_Response(response_timestamp);


-- -----------------------------------------------------------------------------
-- TABLE: Data_Quality_Report
-- Stores quality reports generated by Agent 2 (Data Quality Agent)
-- One report per visit
-- -----------------------------------------------------------------------------
CREATE TABLE Data_Quality_Report (
    report_id INT PRIMARY KEY AUTO_INCREMENT,
    visit_id INT NOT NULL UNIQUE,
    data_quality_status VARCHAR(50) NOT NULL CHECK (data_quality_status IN ('PASS', 'NEEDS_COMPLETION', 'LOW_CONFIDENCE')),
    confidence_score DECIMAL(3, 2) NOT NULL CHECK (confidence_score >= 0 AND confidence_score <= 1),
    missing_fields JSON,  -- List of missing field names
    inconsistent_fields JSON,  -- List of inconsistency objects
    clarification_required BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (visit_id) REFERENCES Visit(visit_id) ON DELETE CASCADE
);

CREATE INDEX idx_quality_status ON Data_Quality_Report(data_quality_status);
CREATE INDEX idx_quality_score ON Data_Quality_Report(confidence_score);
CREATE INDEX idx_quality_clarification ON Data_Quality_Report(clarification_required);


-- -----------------------------------------------------------------------------
-- TABLE: Clarification_Request
-- Stores pending clarification requests to be sent to patients via Agent 1
-- -----------------------------------------------------------------------------
CREATE TABLE Clarification_Request (
    clarification_id INT PRIMARY KEY AUTO_INCREMENT,
    visit_id INT NOT NULL,
    question_id VARCHAR(100) NOT NULL,
    reason TEXT,  -- Why clarification is needed
    status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'answered', 'expired')),
    triggered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMP NULL,
    answered_at TIMESTAMP NULL,
    response TEXT NULL,  -- The clarified response
    
    FOREIGN KEY (visit_id) REFERENCES Visit(visit_id) ON DELETE CASCADE
);

CREATE INDEX idx_clarification_visit ON Clarification_Request(visit_id);
CREATE INDEX idx_clarification_status ON Clarification_Request(status);
CREATE INDEX idx_clarification_question ON Clarification_Request(question_id);


-- -----------------------------------------------------------------------------
-- TABLE: Adverse_Event
-- Stores adverse event/symptom data reported by patients
-- -----------------------------------------------------------------------------
CREATE TABLE Adverse_Event (
    event_id INT PRIMARY KEY AUTO_INCREMENT,
    visit_id INT NOT NULL,
    symptom_description TEXT NOT NULL,
    severity VARCHAR(50) CHECK (severity IN ('mild', 'moderate', 'severe', 'life-threatening')),
    time_to_onset VARCHAR(100),
    body_parts JSON,  -- List of affected body parts
    safety_flag BOOLEAN DEFAULT FALSE,
    reported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (visit_id) REFERENCES Visit(visit_id) ON DELETE CASCADE
);

CREATE INDEX idx_adverse_visit ON Adverse_Event(visit_id);
CREATE INDEX idx_adverse_severity ON Adverse_Event(severity);
CREATE INDEX idx_adverse_safety ON Adverse_Event(safety_flag);


-- -----------------------------------------------------------------------------
-- TABLE: Form_Submission
-- Tracks email forms sent to patients and their submission status
-- Used for dual-channel communication (WhatsApp + Email Form)
-- -----------------------------------------------------------------------------
CREATE TABLE Form_Submission (
    submission_id INT PRIMARY KEY AUTO_INCREMENT,
    visit_id INT NOT NULL,
    patient_id VARCHAR(50) NOT NULL,
    form_type VARCHAR(50) NOT NULL CHECK (form_type IN ('initial', 'clarification')),
    form_token VARCHAR(100) NOT NULL UNIQUE,
    form_url VARCHAR(500),
    language VARCHAR(10) DEFAULT 'en',
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sent_via VARCHAR(20) DEFAULT 'email' CHECK (sent_via IN ('email', 'whatsapp', 'both')),
    filled_at TIMESTAMP NULL,
    responses JSON,                              -- Stored form responses
    missing_questions JSON,                      -- For clarification forms
    status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'filled', 'expired')),
    
    FOREIGN KEY (visit_id) REFERENCES Visit(visit_id) ON DELETE CASCADE,
    FOREIGN KEY (patient_id) REFERENCES Patient(patient_id) ON DELETE CASCADE
);

CREATE INDEX idx_form_visit ON Form_Submission(visit_id);
CREATE INDEX idx_form_patient ON Form_Submission(patient_id);
CREATE INDEX idx_form_token ON Form_Submission(form_token);
CREATE INDEX idx_form_status ON Form_Submission(status);


-- =============================================================================
-- SAMPLE DATA FOR TESTING
-- =============================================================================

-- Insert sample patient
INSERT INTO Patient (patient_id, name, phone_number, age, gender) VALUES
('P001', 'John Doe', '+919876543210', 45, 'male'),
('P002', 'Jane Smith', '+919876543211', 32, 'female');

-- Insert sample doctor
INSERT INTO Doctor (doctor_id, name, department, hospital_id) VALUES
(1, 'Dr. Sharma', 'Cardiology', 101),
(2, 'Dr. Patel', 'General Medicine', 101);

-- Insert sample visit
INSERT INTO Visit (visit_id, patient_id, doctor_id, visit_date, visit_type, disease_name, status) VALUES
(1, 'P001', 1, '2026-01-08', 'new', 'Hypertension', 'completed'),
(2, 'P002', 2, '2026-01-08', 'follow-up', 'Diabetes', 'in_progress');

-- Insert sample doctor entry
INSERT INTO Doctor_Entry (visit_id, diagnosis_notes, medicine_prescribed, dosage, frequency, duration) VALUES
(1, 'Blood pressure elevated, starting medication', 'Amlodipine', '5mg', 'Once daily', '30 days'),
(2, 'Blood sugar levels improving', 'Metformin', '500mg', 'Twice daily', '60 days');

-- Insert sample patient responses
INSERT INTO Patient_Response (visit_id, question_id, answer, language) VALUES
(1, 'Q1_language', 'english', 'english'),
(1, 'Q2_medicine_started', 'yes', 'english'),
(1, 'Q3_adherence', 'daily', 'english'),
(1, 'Q4_food_relation', 'after food', 'english'),
(1, 'Q5_new_symptoms', 'no', 'english'),
(1, 'Q9_safety_check', 'confirmed', 'english');

-- Insert sample quality report
INSERT INTO Data_Quality_Report (visit_id, data_quality_status, confidence_score, missing_fields, inconsistent_fields, clarification_required) VALUES
(1, 'PASS', 1.00, '[]', '[]', FALSE);


-- =============================================================================
-- USEFUL VIEWS
-- =============================================================================

-- View: Visit Summary with Quality Status
CREATE VIEW vw_visit_quality_summary AS
SELECT 
    v.visit_id,
    v.visit_date,
    v.visit_type,
    v.disease_name,
    p.name AS patient_name,
    p.phone_number,
    d.name AS doctor_name,
    COALESCE(dqr.data_quality_status, 'PENDING') AS quality_status,
    COALESCE(dqr.confidence_score, 0) AS confidence_score,
    dqr.clarification_required
FROM Visit v
LEFT JOIN Patient p ON v.patient_id = p.patient_id
LEFT JOIN Doctor d ON v.doctor_id = d.doctor_id
LEFT JOIN Data_Quality_Report dqr ON v.visit_id = dqr.visit_id;


-- View: Pending Clarifications
CREATE VIEW vw_pending_clarifications AS
SELECT 
    cr.clarification_id,
    cr.visit_id,
    cr.question_id,
    cr.reason,
    cr.triggered_at,
    p.name AS patient_name,
    p.phone_number
FROM Clarification_Request cr
JOIN Visit v ON cr.visit_id = v.visit_id
JOIN Patient p ON v.patient_id = p.patient_id
WHERE cr.status = 'pending';


-- View: Low Confidence Visits Requiring Review
CREATE VIEW vw_low_confidence_visits AS
SELECT 
    v.visit_id,
    v.visit_date,
    p.name AS patient_name,
    d.name AS doctor_name,
    dqr.confidence_score,
    dqr.missing_fields,
    dqr.inconsistent_fields
FROM Data_Quality_Report dqr
JOIN Visit v ON dqr.visit_id = v.visit_id
JOIN Patient p ON v.patient_id = p.patient_id
JOIN Doctor d ON v.doctor_id = d.doctor_id
WHERE dqr.data_quality_status = 'LOW_CONFIDENCE'
ORDER BY dqr.confidence_score ASC;
